### ISSUE TITLE
Lazy blockquote does not work

### ISSUE THREAD

**Issue by morimoriysmoon** [remarkjs/remark-gfm#13] opened 2021-04-14 04:26 UTC
### Subject of the issue

Lazy blockquote does not work on react-markdown if this plugin is applied.

### Your environment

*   **OS**: Windows 10
*   **Packages**: react-markdown 5.0.3, remark-gfm 1.0.0
*   **Env**: React v17.0.2

### Steps to reproduce

Use below markdown text.

    Markdown allows you to be lazy and only put the `>` before the first
    line of a hard-wrapped paragraph:

    > This is a blockquote with two paragraphs. Lorem ipsum dolor sit amet,
    consectetuer adipiscing elit. Aliquam hendrerit mi posuere lectus.
    Vestibulum enim wisi, viverra nec, fringilla in, laoreet vitae, risus.

    > Donec sit amet nisl. Aliquam semper ipsum sit amet velit. Suspendisse
    id sem consectetuer libero luctus adipiscing.

### Expected behavior

![image](https://user-images.githubusercontent.com/1762090/114656239-0bb06500-9d31-11eb-89c4-7e7369429231.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/1762090/114654339-4e703e00-9d2d-11eb-8e1a-6524807a6720.png)

**Comment by Sanbala** [comment] 2021-04-16 04:24
I'm facing the same issue. Is there are any workaround or fix available?

**Comment by wooorm** [comment] 2021-04-16 06:59
This is the same issue as GH-3, so see my last comment there: https://github.com/remarkjs/remark-gfm/issues/3#issuecomment-789814194

**Comment by wooorm** [comment] 2021-05-18 15:02
Duplicate of #3

**Closed by wooorm** 2021-05-18 15:02 UTC
Labels: 🐛 type/bug, 🔍 status/open
