### ISSUE TITLE
Table parse issue

### ISSUE THREAD

**Issue by tfsomrat** [remarkjs/remark-gfm#58] opened 2023-09-20 06:27 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

4.0.0

### Steps to reproduce

After updating it from 3.0.1 to 4.0.0, I am getting an error "Cannot set properties of undefined (setting 'inTable')". it works fine on version 3.

this is my code 
```
import { MDXRemote } from "next-mdx-remote/rsc";
import remarkGfm from "remark-gfm";

const MDXContent = ({ content }: { content: any }) => {
  const mdxOptions = {
    remarkPlugins: [remarkGfm],
  };

  return (
    <>
      <MDXRemote
        source={content}
        options={{ mdxOptions }}
      />
    </>
  );
};

export default MDXContent;
```

### Expected behavior

the table should render

### Actual behavior

getting error `Cannot set properties of undefined (setting 'inTable')`

### Runtime

Node v17

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Next.js

**Comment by activatedgeek** [comment] 2023-09-20 08:44
See also #57.

**Comment by ChristianMurphy** [comment] 2023-09-20 09:08
Duplicate of https://github.com/remarkjs/remark-gfm/issues/57

**Closed by ChristianMurphy** 2023-09-20 09:08 UTC
Labels: 🤞 phase/open

**Comment by ChristianMurphy** [comment] 2023-09-20 09:10
A major version release is rolling out across all: `mdx`, `unified`, `remark`, `rehype`, and `micromark` packages.
This includes both type changes (static analysis error) and changes to the parser (potential runtime error) if the major versions are mismatched.

Hold on version 3 of remark-gfm, until the next major of MDX is released
