### ISSUE TITLE
support new GFM alerts

### ISSUE THREAD

**Issue by matifali** [remarkjs/remark-gfm#62] opened 2023-12-20 07:52 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Support the [new GitHub Alters notation](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts). There were previous requests in #53 and #54.

> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.

### Solution

Have native support for this notation.

### Alternatives

An alternative library is [remark-github-beta-blockquote-admonitions](https://github.com/myl7/remark-github-beta-blockquote-admonitions)

**Comment by wooorm** [comment] 2023-12-20 08:10
Duplicate of #53

**Closed by wooorm** 2023-12-20 08:10 UTC
Labels: 🤞 phase/open

**Comment by wooorm** [comment] 2023-12-20 08:12
That is not an extension to GFM so doesn’t go here.
Instead, it’s something that would go in rehypejs/rehype-github, or as you mentioned, in another plugin.

**Comment by calumk** [comment] 2024-01-17 13:07
For future reference, plugin here : https://github.com/chrisweb/rehype-github-alerts
