### ISSUE TITLE
TypeError: Cannot read property '3' of undefined

### ISSUE THREAD

**Issue by Wekananda** [remarkjs/remark-gfm#22] opened 2021-08-15 10:20 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.0

### Steps to reproduce

Here my code

import React from "react";
import Markdown from "react-markdown";

import gfm from "remark-gfm";
import raw from "rehype-raw";

const markdownSource = `
<span style="background: green">working example</span>
`;

export default function App() {
  return (
    <Markdown remarkPlugins={[gfm]} rehypePlugins={[raw]}>
      {markdownSource}
    </Markdown>
  );
}

### Expected behavior

Package/plugin loaded without error

### Actual behavior

Got error TypeError: Cannot read property '3' of undefined

![image](https://user-images.githubusercontent.com/21331447/129475213-a96aab3b-58c4-4b81-b1fc-9ceef4773c37.png)

### Runtime

Node v16

### Package manager

npm v7

### OS

Windows

### Build and bundle tools

Next.js

**Comment by wooorm** [comment] 2021-08-15 10:28
Duplicate of #21!

**Closed** 2021-08-15 10:27 UTC
Labels: 👯 no/duplicate, 👎 phase/no
