### ISSUE TITLE
Lazy blockquote is rendered as codeblock instead blockquote

### ISSUE THREAD

**Issue by Sanbala** [remarkjs/remark-gfm#14] opened 2021-04-16 08:40 UTC
### Subject of the issue

Lazy blockquote is not rendered correctly in remark-gfm

### Your environment

*   **OS**:  windows 10
*   **Packages**:  remark-gfm-1.0.0
*   **Env**:  node-v11.15.0

### Steps to reproduce

Add a blockquote text followed by a lazy blockquote text. Without using remark-gfm, it is working as expected but when remark-gfm is used, it is rendering incorrectly

Sample Application: https://codesandbox.io/s/remark-rehype-debug-forked-w83b8?file=/src/index.js

### Expected behavior

Lazy blockquote should also be rendered as blockquote

![image](https://user-images.githubusercontent.com/32705479/114997364-5f4fb980-9ebd-11eb-8b35-8ab19e035453.png)

### Actual behavior

Lazy blockquote should also be rendered as codeblock

![image](https://user-images.githubusercontent.com/32705479/114997421-71315c80-9ebd-11eb-9a53-ebfb75c9effa.png)

**Comment by wooorm** [comment] 2021-05-18 15:02
Duplicate of #3

**Closed by wooorm** 2021-05-18 15:02 UTC
Labels: 🐛 type/bug, 🔍 status/open
