### ISSUE TITLE
Client Side Exception after upgrading to v 4.0.0

### ISSUE THREAD

**Issue by DevikaM** [remarkjs/remark-gfm#65] opened 2024-05-22 21:10 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

4.0.0

### Steps to reproduce

When using in combination with `react-markdown`: 

``` 
<ReactMarkdown ... remarkPlugins={[remarkGfm]}>
  {markdown}
</ReactMarkdown>
```

### Expected behavior

Markdown should render

### Actual behavior

After upgrading package to 4.0.0, I'm getting a client error:

<img width="1728" alt="sh" src="https://github.com/remarkjs/remark-gfm/assets/14219591/7c98f57e-062d-40e5-bbae-2491093aecbb">

<img width="1728" alt="console" src="https://github.com/remarkjs/remark-gfm/assets/14219591/838395ab-b4c7-45e7-9b1d-19a4aa781fc6">

### Runtime

Node v14

### Package manager

yarn 1

### OS

macOS

**Comment by ChristianMurphy** [comment] 2024-05-22 21:20
Duplicate of https://github.com/remarkjs/remark-gfm/issues/57

**Closed** 2024-05-22 21:21 UTC
Labels: 👯 no/duplicate, 👎 phase/no
