### ISSUE TITLE
Support GFM Alerts

### ISSUE THREAD

**Issue by calumk** [remarkjs/remark-gfm#63] opened 2024-01-12 13:47 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

GFM Alerts are not supported 

### Solution

Support GFM Alerts

https://github.com/orgs/community/discussions/16925

eg : 

> [!NOTE]
> This is a note

> [!IMPORTANT]
> This is important

```
> [!NOTE]
> This is a note

> [!IMPORTANT]
> This is important
```

### Alternatives

n/a

**Comment by JounQin** [comment] 2024-01-12 13:55
Duplicate of #53

Please search issues first next time.

**Closed by JounQin** 2024-01-12 13:55 UTC
Labels: 🤞 phase/open

**Comment by JounQin** [comment] 2024-01-12 14:05
Duplicate of #53
