### ISSUE TITLE
iPad Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by farzadso** [remarkjs/remark-gfm#70] opened 2024-10-12 00:40 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-gfm -> 4.0.0

### Link to runnable example

https://codesandbox.io/p/devbox/sparkling-rgb-rlzl7c

### Steps to reproduce

The page no longer loads on an iPad when you add the remark-gfm plugin to react-markdown.

It only happens on iPads

![CleanShot 2024-10-11 at 20 33 51](https://github.com/user-attachments/assets/c6879d0e-d459-4f79-813a-49f1225b19ea)

### Expected behavior

It should render with a fallback.

### Actual behavior

This is the error message it throws:

​`
SyntaxError: Invalid regular expression: invalid group specifier name
`

You can test it by loading this link in an iPad:

https://r7y53f-5173.csb.app/

More logs:

![CleanShot 2024-10-11 at 20 39 27](https://github.com/user-attachments/assets/69db9a5f-a30f-49d5-b378-b1e1e4eeb189)

### Affected runtime and version

node@20+

### Affected package manager and version

npm, yarn and pnpm are the same 

### Affected OS and version

iPad

**Comment by ChristianMurphy** [comment] 2024-10-12 01:07
Duplicate of https://github.com/syntax-tree/mdast-util-gfm-autolink-literal/issues/10

**Closed by ChristianMurphy** 2024-10-12 01:07 UTC
Labels: 🤞 phase/open
