### ISSUE TITLE
Bad performance with long strings with gfm plugin enabled on react-markdown

### ISSUE THREAD

**Issue by angel-git** [remarkjs/remark-gfm#48] opened 2023-01-18 11:07 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.0.1

### Steps to reproduce

https://github.com/angel-git/remark-issue

### Expected behavior

When enabling the plugin the render takes around 30 seconds

### Actual behavior

It shouldn't take so many seconds to render:
![image](https://user-images.githubusercontent.com/1565058/213155089-d79601eb-b928-49ac-ae3f-b2edc5d08fcb.png)

When removing the plugin like:

```
 <Markdown remarkPlugins={[]}>{markdownSource}</Markdown>
```
it renders instantly

is there some setting or something i could do to make it faster?

thanks

### Runtime

Node v16

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Create React App

**Comment by ChristianMurphy** [comment] 2023-01-18 16:15
Duplicate of https://github.com/remarkjs/remark-gfm/issues/45, https://github.com/micromark/micromark-extension-gfm-table/issues/6, and https://github.com/micromark/micromark-extension-gfm-table/issues/9
The response continues to be:

> There is also a need for a completely compliant and safe markdown parser. AFAIK few parsers are as correct in edge cases as micromark. If performance is really important, consider looking at the Rust version of micromark: https://github.com/wooorm/markdown-rs

- https://github.com/micromark/micromark-extension-gfm-table/issues/6#issuecomment-1328063582

If you have specific recommendations on improving performance while keeping inline with GFM spec and being a safe parser, those recommendations are welcome.

**Closed by ChristianMurphy** 2023-01-18 16:15 UTC
Labels: 🤞 phase/open
