### ISSUE TITLE
Markdown [https://www.twilio.com/](https://www.twilio.com/) links are not rendered as expected

### ISSUE THREAD

**Issue by sunknudsen** [remarkjs/remark-gfm#7] opened 2021-01-31 23:41 UTC
### Subject of the issue

Let's say we have the following markdown.

```markdown
Go to [https://www.twilio.com/](https://www.twilio.com/) and sign up.
```

`[https://www.twilio.com/](https://www.twilio.com/)` is rendered as `[https://www.twilio.com/](https://www.twilio.com/)` vs a `https://www.twilio.com/` hyperlink with a `https://www.twilio.com/` `href`.

![Screen Shot 2021-01-31 at 6 37 35 PM](https://user-images.githubusercontent.com/2117655/106401699-6d914c00-641d-11eb-8b8f-5ef5ac2d6f7a.png)

### Your environment

*   **OS**: macOS Catalina `10.15.7`
*   **Packages**: `react-markdown` and `remark-gfm`
*   **Env**: Node `14.15.1` and npm `6.14.11`

### Steps to reproduce

This should be pretty straightforward to reproduce using above markdown.

### Expected behavior

`[https://www.twilio.com/](https://www.twilio.com/)` should be rendered as `https://www.twilio.com/` hyperlink with a `https://www.twilio.com/` `href`.

### Actual behavior

`[https://www.twilio.com/](https://www.twilio.com/)` is rendered as `[https://www.twilio.com/](https://www.twilio.com/)`.

**Comment by ChristianMurphy** [comment] 2021-01-31 23:48
The issue is related to autolink literals, this issue is being tracked at https://github.com/micromark/micromark-extension-gfm-autolink-literal/issues/5 and a possible solution in the works at https://github.com/micromark/micromark-extension-gfm-autolink-literal/pull/6
closing this issue, as it isn't actionable at the `remark-gfm` level and will be resolved in `micromark-extension-gfm-autolink-literal`

**Closed by ChristianMurphy** 2021-01-31 23:48 UTC
Labels: 🐛 type/bug, 🔍 status/open

**Comment by ChristianMurphy** [comment] 2021-01-31 23:50
There's also a potential work around described here: https://github.com/remarkjs/remark-gfm/issues/6#issuecomment-767775803

**Comment by sunknudsen** [comment] 2021-01-31 23:52
Thanks for the heads-up @ChristianMurphy. Thankfully, I "own" the content and used `\[(http.*?)\]\(\1\)` to find and replace links to `$1`.
