### ISSUE TITLE
Table parse error when using vite

### ISSUE THREAD

**Issue by Saul-Mirone** [remarkjs/remark-gfm#39] opened 2022-07-05 04:00 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark@14.0.2, remark-gfm@3.0.1

### Link to runnable example

https://stackblitz.com/edit/typescript-3aqowy?file=index.ts,index.html

### Steps to reproduce

https://stackblitz.com/edit/typescript-3aqowy?file=index.ts,index.html

One interesting thing is that in [codesandbox](https://codesandbox.io/s/dark-paper-2fyj1o), everything works fine. Maybe it's related to bundle strategy for different types of modules?

### Expected behavior

The table should be parsed as

```markdown
| a  | b  | c  |
| :- | :- | :- |
| -- | -- | -- |
| 1  | -- | 3  |
```

Just one node in AST.

### Actual behavior

```markdown
\| a | b | c |

| :- | :- | :- |
| -- | -- | -- |
| 1 | -- | 3 |
```

There're two nodes, one paragraph, one table.

### Runtime

Other (please specify in steps to reproduce)

### Package manager

pnpm

### OS

macOS

### Build and bundle tools

Vite

**Comment by wooorm** [comment] 2022-07-05 07:16
Thanks, I can reproduce this. Seems to be something about the second “delimiter row” that messes with the first.
It’s a problem in `micromark-extension-gfm-table`, if anyone is interested in diving in.

**Comment by 4-1-1** [comment] 2022-07-25 11:27
> Thanks, I can reproduce this. Seems to be something about the second “delimiter row” that messes with the first. It’s a problem in `micromark-extension-gfm-table`, if anyone is interested in diving in.

Try a lot, read the code again and again .  too hard  :sob:

**Comment by wooorm** [comment] 2022-07-31 18:31
I checked a smaller reproduction today, and found the root cause of it: `micromark-extension-gfm-table`.

Closing this here in favor of an issue in the correct repo: https://github.com/micromark/micromark-extension-gfm-table/issues/7.

**Closed by wooorm** 2022-07-31 18:31 UTC
Labels: 🤞 phase/open
