### ISSUE TITLE
 Cannot set properties of undefined (setting 'inTable')

### ISSUE THREAD

**Issue by tujger** [remarkjs/remark-gfm#59] opened 2023-09-21 19:32 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-gfm 4.0.0

### Steps to reproduce

With react-markdown

Doing:

    <Markdown
      children={`| Type | Count |\n| :- | -: |\n`
          + rows.map(item => `| ${item.join(" | ")} |`).join("\n")}
      />

causes the exception below.
Downgrading to 3.0.1 solves the problem.

### Expected behavior

Render the table.

### Actual behavior

    Uncaught TypeError: Cannot set properties of undefined (setting 'inTable')
        at Object.enterTable (index.js:76:1)
        at compile (index.js:351:1)
        at fromMarkdown (index.js:192:1)
        at parser (index.js:18:1)
        at Function.parse (index.js:262:1)
        at ReactMarkdown (react-markdown.js:104:1)
        at renderWithHooks (react-dom.development.js:14141:1)
        at mountIndeterminateComponent (react-dom.development.js:17432:1)
        at beginWork (react-dom.development.js:18728:1)
        at HTMLUnknownElement.callCallback (react-dom.development.js:3733:1)

### Runtime

Node v17

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Webpack, Create React App

**Comment by ChristianMurphy** [comment] 2023-09-21 19:36
Duplicate of https://github.com/remarkjs/remark-gfm/issues/57

**Comment by ChristianMurphy** [comment] 2023-09-21 19:37
Please look at the pinned issue before opening a new one.
To reiterate from the existing issue:

A major version release is rolling out across all: `mdx`, `unified`, `remark`, `rehype`, and `micromark` packages.
This includes both type changes (static analysis error) and changes to the parser (potential runtime error) if the major versions are mismatched.

Hold on version 3 of remark-gfm, until the next major of react markdown is released

**Closed by ChristianMurphy** 2023-09-21 19:36 UTC
Labels: 🤞 phase/open
