### ISSUE TITLE
Support for alert syntax?

### ISSUE THREAD

**Issue by dereckmezquita** [remarkjs/remark-gfm#54] opened 2023-09-03 00:30 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I would like if we could add support for alert syntax as in the github flavoured markdown shown here: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

### Solution

Processing the markdown should also add alerts.

> [!NOTE]
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]
> Crucial information necessary for users to succeed.

> [!WARNING]
> Critical content demanding immediate user attention due to potential risks.

### Alternatives

Another plugin could be created but I think this feature fits nicely here.

**Comment by remcohaszing** [comment] 2023-09-03 08:18
Duplicate of #53

**Closed by remcohaszing** 2023-09-03 08:18 UTC
Labels: 🤞 phase/open
