### ISSUE TITLE
TypeError: Cannot read property '18' of undefined

### ISSUE THREAD

**Issue by chenxsan** [remarkjs/remark-gfm#24] opened 2021-09-02 12:17 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

`remark-gfm` 2.0.0

### Steps to reproduce

1. clone code from https://github.com/webpack/webpack.js.org/pull/5396
2. run `yarn`
3. run `yarn start`

### Expected behavior

No error.

### Actual behavior

Errors like `Cannot read property '29' of undefined` show up many times. For example, https://github.com/webpack/webpack.js.org/pull/5396/checks?check_run_id=3495415399#step:5:3025.

FYI we don't use `react-markdown`, so it might not be related to https://github.com/remarkjs/remark-gfm/issues/22. And the error is not helpful at all, so I don't know how to track it down the problem.

### Runtime

Node v12

### Package manager

yarn v1

### OS

Linux

### Build and bundle tools

Webpack

**Comment by ChristianMurphy** [comment] 2021-09-02 12:49
> Cannot read property '18' of undefined

> the error is not helpful at all, so I don't know how to track it down the problem.

It sounds like an error coming from micromark.
Micromark has a production build and a debug build (which produces nicer errors) https://github.com/micromark/micromark#api
You can access the debug build by adding `--conditions development` to the node call which runs remark/micromark.

**Comment by chenxsan** [comment] 2021-09-02 13:21
There's no error with the lower version `remark-gfm`. My plan in that pull request is to migrate all remark plugins to the ESM versions, so downgrading would be my last resort.

Anyway I've tried replacing `@mdx-js/loader@2.0.0-next.9` with `xdm`, that errors were gone. So it might be the cause.

**Comment by wooorm** [comment] 2021-10-03 15:23
Closing this as it’s more of an external issue. mdx-js should soon be up to do btw!

**Closed by wooorm** 2021-10-03 15:23 UTC
Labels: 🤞 phase/open

**Comment by RomanHotsiy** [comment] 2021-10-16 11:10
I'm using the latest `next.9` version of `mdx-js` with `remark-gfm@3.0.0` and still getting this error.

@wooorm is it expected?

Maybe it's worth to keep either this issue open or open an issue in mdx-js repo so this won't get missed for the 2.0 release of mdx-js?

Also, do you know the root cause of the issue or do you need help to find it out? I'd be happy to help 🙌
